### ISSUE TITLE
Typo in requirements.txt

### ISSUE THREAD

**Issue by jakescally** [qilimanjaro-tech/Circopt-RL-ZXCalc#1]
`ERROR: Could not find a version that satisfies the requirement tensoboard==2.12.1 (from versions: none)
ERROR: No matching distribution found for tensoboard==2.12.1`

This error appears when installing requirements.txt using the installation.py script. Missing "r" in tensorboard. Making the change fixes this error.

Please update requirements.txt to say `tensorboard==2.12.1` instead of `tensoboard==2.12.1`.

**Comment by jng164** [comment]
Thank you for noticing! The typo is now fixed 👍
